### ISSUE TITLE
incorrect repository name

### ISSUE THREAD

**Issue by danmarsden** [pch312/moodle-bloc-accessibilite#1]
Your repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "block_accessibilite" the correct name to use would be: "moodle-block_accessibilite"

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top.

**Comment by pch312** [comment]
Rename the repository
