### ISSUE TITLE
function names must follow frankenstyle naming rules

### ISSUE THREAD

**Issue by danmarsden** [pch312/moodle-bloc-accessibilite#7]
the functions "read()" and "store()" could clash with internal Moodle functions - all functions within a plugin must use our naming conventions by either prefixing the functino with the frankenstyle plugin name, or be in name spaced classes.

for more information see:
https://docs.moodle.org/dev/Frankenstyle

Please note this is a blocker for plugins db approval

**Comment by pch312** [comment]
rename the functions
